### ISSUE TITLE
what is happening?would you like to help me,please?

### ISSUE THREAD

**Issue by daima2017** [Immortals88/time-EA#3]
hi my friend,your code is interesting,
i run it,but a bug was coming,such as,

Traceback (most recent call last):
  File "D:###DualMatch-master/main.py", line 291, in <module>
    dto.saveobj(time_sim, fn)
  File "D:###\DualMatch-master\dto.py", line 34, in saveobj
    pickle.dump(obj, f, protocol=pickle.HIGHEST_PROTOCOL)
TypeError: can't pickle _thread.RLock objects

would you like to help me,please?
![image](https://user-images.githubusercontent.com/44838048/185738881-e200a385-4b51-4473-a84f-23c6d0c6f777.png)

**Comment by joker-xii** [comment]
It's probably a problem with saving the intermediate results, and the code can run on our platform. We are looking into it.
Besides, a quick fix is to erase that line of code since its purpose is to save the intermediate result to save some time. Without it, the temporal similarity is calculated for every time the program runs so that it may run slower.

**Comment by daima2017** [comment]
anthor bug~~~
![image](https://user-images.githubusercontent.com/44838048/185754624-d2474489-05ad-40c6-b127-2e2629383ce9.png)

**Comment by joker-xii** [comment]
Maybe the bug is related to the version of packages. We will release a ``requirements.txt`` file for users to create a similar environment.
